### ISSUE TITLE
Estrutura de Pastas

### ISSUE THREAD

**Issue by movibe** [SauloSilva/bbs#22]
Gostaria da opnião de vocês sobre essa sugestão de organização das pastas da aplicação.

# app

Pasta principal com os códigos fontes

## app/component

Componentes que são compartilhados entre toda a aplicação.

## app/component/logo
Cada componente é separado por uma pasta, dentro dela terá sempre um arquivo index.js e outro style.js que corresponde ao componente.

- app/component/logo
-- index.js
-- style.js

Caso o componente tenha diferente versão para outras plataformas, os arquivos serão de acordo com cada versão de plataforma exemplo:

- app/component/logo
-- index.android.js
-- style.android.js
-- index.ios.js
-- style.ios.js
-- index.wp.js
-- style.wp.js

## app/config

Arquivos estáticos de configuração.

## app/helper

Scripts ou funções reutilizáveis pela aplicação

## app/layout
Scripts ou componentes responsáveis pelo layout da aplicação. Exemplo: drawer/tab/form/label

### app/module
Sistema modular de páginas da aplicação, em que um módulo pode ter uma ou mais paginas, e componentes compartilhados apenas entre suas páginas, tornando mais simples a injeção de futuros módulos.

### app/module/{primary/page}

O sistema de pasta de módulos pode corresponder diretamente á uma página ou um grupo de páginas da aplicação, seguindo o padrão de criação de componentes com versões multi plataforma ou específicos para cada plataforma.

### app/module/intro
Módulo de intro, corresponde á uma página de apresentação da aplicação, aquela com slide das funcionalidades quando o usuário entra pela primeira vez, nesse caso podemos dividir suas página de acordo com a plataforma seguindo o padrão de componentes

### app/module/auth
Já o módulo de auth, é um grupo de módulos, responsáveis pelas páginas de login, cadastro, recuperação de senha e diferentes formas de autenticação como digital ou reconhecimento fácil

## app/redux

Pasta central da lógica redux compartilhada na aplicação

## app/services

Serviços compartilhado entre a aplicação

**Comment by SauloSilva** [comment]
@movibe ficou muito bom, no momento nada a acrescentar nestes itens.
@ArmandoAssuncao e pra tu ok também?
