### ISSUE TITLE
Background Gradient

### ISSUE THREAD

**Issue by movibe** [SauloSilva/bbs#32]
Criei um componente de Fundo Gradient, ele já tem uma cor padrão, mas pode ser alterado com nos exemplos abaixo:

```js
import React from 'react'
import {Text, View} from 'react-native';
import Background from '@component/BackgroundGradient'
import style from './style'

class AuthLoginScreen extends React.Component {
  
  static navigationOptions = {
    title: 'Login',
    headerStyle: {
      backgroundColor: 'transparent',
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      borderBottomWidth: 0 // removes the border on the bottom
    },
    headerTintColor: '#fff'
  };
  
  render() {
    return (
      <Background>
        <View style={style.main}>
          <Text>Hello World</Text>
          <Text style={style.buttonText}>
            Sign in with Facebook
          </Text>
        </View>
      </Background>
    );
  }
}

export default AuthLoginScreen


```
![IntroScreen](https://lh3.googleusercontent.com/jNrY9AmxgQ4pn0xgI2d7CdMJctWDttGxCBMykMUg0ueg50ufJKqggaD6U-BBYwliV0p2jAMym7AQOg=s0 "IntroScreen")

**Comment by movibe** [comment]
Exemplo na Intro

![IntroSample](https://lh3.googleusercontent.com/4tejqerwYTvFXhCFm13zot0mxs09Cv6P2V0wgiwvGNb7HjPVLsEV_rDoaBnT_F_o5uTVf-1ixvO7Cw=s0 "IntroSample")


Exemplo com outra cor

```js
<Background from="#0099cc" to="#006699"></Background>
```
![IntroOtherCOlor](https://lh3.googleusercontent.com/KVa107Bd6vCPrn2euhHCiXfRKZAb9PJ8YwV_DGLYOR8wk426SuwSliX6VCeSaocO1T-kfv2S_yKnDw=s0 "IntroOtherColor")

**Comment by SauloSilva** [comment]
ficou show
